### PR TITLE
Fix the bug when baseurl isn't empty string.

### PR DESCRIPTION
**Pull request by sleepingpig**
If baseurl isn't empty string in _config.yml, it will fail to load the "menu.svg".

### CODE REVIEW

**Comment by jhabdas** [comment]
@sleepingpig `baseurl` should be `Nil` when site not hosted in a subpath. This is a common misunderstanding for Jekyll themes. Oftentimes theme maintainers workaround this shortcoming with a comment like this: https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml#L15

**Comment by jhabdas** [comment]
Here ya go. Straight from the 🐴 mouth (one of them, at least): https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/

**Comment by tomschenkjr** [comment]
I'm able to replicate this issue as well when deploying to a subpath (i.e., `gh-pages`). Using "github.io" as the `url` and "\edition-jekyll-template" as `baseurl`--as recommended--the resulting webpage is unable to find "menu.svg".

[Here is the config.yaml file](https://github.com/tomschenkjr/edition-jekyll-template/blob/master/_config.yml#L5-L6) for the minimal reproducible example and the [resulting rendered web page](https://tomschenkjr.github.io/edition-jekyll-template/). View on the console for the 404 error.

**Comment by mneumegen** [comment]
Thanks for letting us know about this. Fixed on master.

**Pull request closed without merging**
